#!/bin/bash
set -ex
yarn build
docker build -t replic.us:local ./


# IMAGE=`docker images | awk '{print $3}' | tail -n+2 | head -n 1`
# CONTAINER=`docker create $IMAGE`
# docker start $CONTAINER
# trap "docker rm -f $CONTAINER" EXIT
# docker cp $CONTAINER:website/dist .
